export default {
  VAT: 'VAT',
  AUDIT_LOG: 'audit_log',
  NOTIFICATION: 'notification',
  GROUP_NOTIFICATION: 'group_notification',
  GROUP: 'Group',
  INDIVIDUAL: 'Individual',
  APPROVED: 'Approved',
  DECLINED: 'Declined',
  NEW_NOTIFICATION: 'New',
  DISPENSE: 'dispense',
  RETURN: 'return',
  GENERATOR_PURCHASE: 'Generator Purchase',
  MAINTENANCE: 'Maintenance',
  OFFICE_EXPENSES: 'Office Expenses',
};
